### ISSUE TITLE
RTMP stream from OSEE GoStream causes OME to crash immediately

### ISSUE THREAD

**Issue by getroot** [AirenSoft/OvenMediaEngine#1631]
### Discussed in https://github.com/AirenSoft/OvenMediaEngine/discussions/1630

<div type='discussions-op-text'>

<sup>Originally posted by **bchah** May 31, 2024</sup>
RTMP or RTMPS streams coming to OME from the [OSEE GoStream Deck](https://osee-tech.com/products/gostream-deck) causes an immediate crash:

```
[2024-05-30 21:35:53.933] I [SPRTMP-t1935:644] Provider | stream.cpp:51   | Unknown/(100) has been started stream
[2024-05-30 21:35:53.934] I [SPRTMP-t1935:644] RTMPProvider | rtmp_provider.cpp:194  | A RTMP client has connected from 
[2024-05-30 21:35:53.944] I [SPRTMP-t1935:644] RTMPProvider | rtmp_stream.cpp:977  | [?InvalidApp?/] ChunkSize is changed to 60000 (stream id: 0)
[2024-05-30 21:35:53.947] W [SPRTMP-t1935:644] RTMPProvider | rtmp_stream.cpp:302  | Could not obtain tcUrl from the RTMP stream: []
[2024-05-30 21:35:53.955] C [SPRTMP-t1935:644] OvenMediaEngine | signals.cpp:124  | OME v0.16.5 ((From archive)) received signal 11 (SIGSEGV), interrupt.
```

Has anybody else tried this new switcher out yet? Besides this issue it's quite feature-packed and priced the same as an ATEM Mini.</div>

**Comment by getroot** [comment]
This is an RTMP metadata compatibility issue. We need to connect that encoder to our server and look at how it sends the metadata. @dimiden

**Comment by bchah** [comment]
Thank you guys, I am happy to assist with sending test streams, providing remote access to connected computers, etc.

**Comment by DimidenAZ** [comment]
@bchah I sent you the RTMP information for the test.

**Comment by dimiden** [comment]
@bchah I sent you the RTMP information for the test.

**Comment by dimiden** [comment]
@bchah
For now, I have fixed the issue where OME was crashed in the eb72d658fcc5d0c12626c6559b3860da568abcf2. The compatibility with OSEE GoStream is still being worked on, and an update will be provided soon.

**Comment by bchah** [comment]
Hi @dimiden, thank you for your work on this. I tried with the latest dev docker image and the crash is still occurring in the same manner, unfortunately. Please let me know if you would like to set up another test stream. Happy to help however I can!

**Comment by dimiden** [comment]
@bchah 
Oooops! I just checked that other parts might have problems too.
I'm sorry, but please double check on the latest version. e76384d43789b561f6cb7fd9404c6184a989a69e

**Comment by bchah** [comment]
Sorry @dimiden, the crash is still occurring from the dev docker image that was just pushed. If you are certain you've fixed the problem, could it be a layer cache issue in your docker build?

**Comment by dimiden** [comment]
@bchah 
Oh, I am really, really sorry.
I tested with the RTMP dump packet you sent earlier and found that the same code is present elsewhere as well.
I was in a hurry yesterday and did not test it thoroughly.
I have committed it 4dbece762078fdec68a2d67042b32ccbcc715cd7, and it should work.

**Comment by dimiden** [comment]
@bchah 
Yes. OME is currently having compatibility issue with OSEE GoStream, so I made sure to disconnect for now.
I'm currently working on the compatibility issue, so I'll let you know when it's updated!
(I don't think it's difficult to solve, but I'm very busy right now, so it'll take a little time.)
