### ISSUE TITLE
Crash due to incorrect MPEG-2 TS input

### ISSUE THREAD

**Issue by getroot** [AirenSoft/OvenMediaEngine#1927]
### Discussed in https://github.com/AirenSoft/OvenMediaEngine/discussions/1926

<div type='discussions-op-text'>

<sup>Originally posted by **racribeiro** September 18, 2025</sup>
I have been evaluating Oven Media Engine for several months and have found it to be a versatile and powerful platform. My primary application involves ingesting UDP/MPEG-TS streams and stream them to LL-HLS, alongside utilizing the WebRTC and recording functionalities.

Operation is generally stable; however, I am experiencing some core dumps when the engine processes malformed or unstable input streams (e.g., corrupted packets, mid-stream source changes). It appears that a single problematic input stream can cause a fatal error in the entire service. This suggests that streams may not be isolated from the main process thread.

This leads me to a few questions about best practices for resilience:

- Is there a recommended fault-tolerant architecture or configuration to prevent a single input stream from crashing the entire server?
- The two-layer (Origin/Edge) architecture is recommended for this reason? 

My assumption is that an Origin server could handle the unstable sources, ensuring only well-behaved (OVT over SRT) streams are passed to the Edge servers that handle client delivery.

I was hoping to implement a simple, single-tier deployment, as my use case doesn't require a massive number of viewers and can be easily handled by a single OME server.

</div>

**Comment by getroot** [comment]
Using the crash dump from @racribeiro , I added some exception handling. I think this should fix the issue. Could you confirm if it’s resolved?

You can test with the master branch, or with Docker using airensoft/ovenmediaengine:dev

**Comment by racribeiro** [comment]
It still crashes, but is much more "quietly" and further down the process of setting up the channel...

using the docker "airensoft/ovenmediaengine:dev".

ome                        | [2025-09-19 17:43:19.848] I [InboundWorker:7778] Monitor | application_metrics.cpp:58   | Create StreamMetrics(stream_4001/3894d2a1-8561-45b0-a7cb-e01397a4f258/#devel#app/stream_4001/o) for monitoring
ome                        | [2025-09-19 17:43:19.851] I [OutboundWorker:7779] WebRTC Publisher | rtc_stream.cpp:237  | WebRTC Stream has been created : stream_4001/3782630530
ome                        | Rtx(false) Ulpfec(false) JitterBuffer(false) PlayoutDelay(false min:0 max: 0)
ome                        | [2025-09-19 17:43:19.852] I [OutboundWorker:7779] LLHLS Publisher | llhls_stream.cpp:1333 | LLHlsStream::ComputeOptimalPartDuration() - Video track(1) FrameRate(32.681896) frame_duration_ms(30.597980) optimal_frame_count(7.000000) part_target(200.000000) optimal_part_target(214.185859)
ome                        | [2025-09-19 17:43:19.852] I [OutboundWorker:7779] LLHLS Publisher | llhls_stream.cpp:1358 | LLHlsStream::AddPackager() - Track(1) ChunkDuration(214.000000)
ome                        | [2025-09-19 17:43:19.852] I [OutboundWorker:7779] LLHLS Publisher | llhls_stream.cpp:228  | LLHlsStream has been created : stream_4001/3782630530
ome                        | OriginMode(true) Chunk Duration(0.20) Segment Duration(1.00) Segment Count(10) DRM(none)
ome                        | Segmentation fault      (core dumped) ./OvenMediaEngine -c conf

**Comment by getroot** [comment]
@racribeiro Could you upload the full log? I need to see the earlier context to debug it accurately.

**Comment by getroot** [comment]
And what command do you use to push with ffmpeg? If I can reproduce it on my end, I can resolve the issue more quickly.

**Comment by getroot** [comment]
Since the crash dump is not appearing in the logs,  
it might be because you’re running an old cached image of airensoft/ovenmediaengine:dev.  
To make sure, please pull the latest image before testing:

docker pull airensoft/ovenmediaengine:dev


From the logs, it seems that STDERR might not be printed. Could you also let me know the exact command you used to run Docker so that I can reproduce the issue on my side?

**Comment by racribeiro** [comment]
It did perform the download and this is the Index Digest: docker.io/airensoft/ovenmediaengine:dev@sha256:6b08ba8c2170d55ee4525be604dfe4f6532c7b86aa2be1dd9adf15015db04d3b

I've tried also the ":latest" and the Behaviour is the same.

I'm getting this on all the files I put in...
https://download.blender.org/demo/movies/BBB/bbb_sunflower_1080p_30fps_normal.mp4.zip

FFMPEG is normal, very basic...

ffmpeg -re -i <file> -map 0 -c:v copy -f mpegts udp://<ip>:<port>

I've tried to increase the logging, but it doesn't show anything more.

Please note that previously I was using a compiled version, that is the reason why, probably, the dump is so detailed.

The Server.xml has the develop virtualhost, live and vod applications. Receives RTMP and UDP, maps udp to ports 4000-4030. No transcoding, no encoding, no hwaccels.

**Comment by getroot** [comment]
Could you upload the full log? I need to see the earlier context to debug it accurately.

**Comment by dimiden** [comment]
@racribeiro 
I tested with [OME 6b08ba8](https://hub.docker.com/layers/airensoft/ovenmediaengine/dev/images/sha256-fa21210ab4a70d3b81dadc9bd5c2475470c116a54f2ecb9507bf17ac0c65f1d8) and FFmpeg 7.0.2 on Ubuntu 20.04, but I was unable to reproduce the issue.
This may occur with a different version of FFmpeg, or it may possibly be related to something other than MPEG-TS.

Therefore, we kindly ask you to provide the "full logs" requested earlier by @getroot, along with the FFmpeg version you used, the "crash dump", and the `Server.xml` file. Having these files intact will allow us to respond more quickly.

- The "full logs" are necessary to understand the circumstances leading up to the issue. They are stored in `/opt/ovenmediaengine/bin/logs` inside the docker container. Please mount this path when running docker and attach the files.
- The "crash dump" is crucial for identifying exactly what went wrong at the time of the issue. It is stored in `/opt/ovenmediaengine/bin/dumps` inside the docker container. Please also attach the files from this directory.
- The `Server.xml` file is requested in case the issue is not related to MPEG-TS. If you have not modified it, attaching it is optional.

We would greatly appreciate your assistance in resolving this issue.

**Comment by sfnk** [comment]
hey guys, 
i can chime in here. had the same crash - then on :dev tag there is no crash, we get this:

[2025-10-01 20:30:06.890] E [SPSRT-s9999:30] MPEGTS_PACKET | mpegts_packet.cpp:443  | Invalid adaptation field length: 254
[2025-10-01 20:30:06.890] E [SPSRT-s9999:30] MPEGTS_PACKET | mpegts_packet.cpp:431  | Invalid mpegts packet size: 1108, consumed: 4
[2025-10-01 20:30:06.890] E [SPSRT-s9999:30] MPEGTS_PACKET | mpegts_packet.cpp:431  | Invalid mpegts packet size: 544, consumed: 127
[2025-10-01 20:30:06.890] E [SPSRT-s9999:30] MPEGTS_PACKET | mpegts_packet.cpp:431  | Invalid mpegts packet size: 872, consumed: 75
[2025-10-01 20:30:06.890] E [SPSRT-s9999:30] MPEGTS_PACKET | mpegts_packet.cpp:431  | Invalid mpegts packet size: 684, consumed: 172
[2025-10-01 20:30:06.925] E [SPSRT-s9999:30] MPEGTS_PACKET | mpegts_packet.cpp:431  | Invalid mpegts packet size: 1388, consumed: 4
[2025-10-01 20:30:06.925] E [SPSRT-s9999:30] MPEGTS_PACKET | mpegts_packet.cpp:431  | Invalid mpegts packet size: 1012, consumed: 4


IIRC receiving this with an FFMPEG instead of OME, you need to set "-flags2 showall" (or ffmpeg sanitized that already).

**Comment by getroot** [comment]
@sfnk Thank you, 

OME supports only the standard MPEG-2 Transport Stream packet size of 188 bytes, as defined in ISO/IEC 13818-1. Other packet sizes such as 192, 204, or 208 bytes are extended formats used in specific applications, and are not supported by OME.

**Comment by getroot** [comment]
There have been numerous crash patches so far, and this issue is expected to disappear in 0.20.0. If the issue persists, please let us know.
