### ISSUE TITLE
Firefox Ice candidate problem

### ISSUE THREAD

**Issue by cheluskin** [AirenSoft/OvenMediaEngine#41]
in logs
`[2019-08-26 19:49:55.195] I 3641 Signalling | rtc_signalling_server.cpp:93   | New client is connected: <ClientSocket: 0x7f2d84252840, #26, state: 4, TCP, [v4] 46.96.4.197:64870>
[2019-08-26 19:49:55.552] W 3641 SDP | session_description.cpp:252  | Unknown Attributes : a=sendrecv
[2019-08-26 19:49:55.671] W 3641 Ice | ice_candidate.cpp:80   | Candidate string does not starts with 'candidate:' string: 
[2019-08-26 19:49:55.671] E 3641 Signalling | rtc_signalling_server.cpp:197  | An error occurred while dispatch command candidate for stream (app/test99): Invalid candidate:  (400), disconnecting...
[2019-08-26 19:49:55.671] I 3641 Signalling | rtc_signalling_server.cpp:240  | Client is disconnected: <WebSocketClient: 0x7f2d84193fe0, <ClientSocket: 0x7f2d84252840, #26, state: 0, TCP, [v4] 46.96.4.197:64870>> (app / test99, ufrag: local: 5iOvHC, remote: 8873d531)
`

in firefox 68.0.2 macOS 10.14.6 

`[[OvenPlayer]] v.0.9.732-2019080617-rev.d5e5268 ovenplayer.js:2:64991
#player 
Object { show: show(), hide: hide(), addClass: addClass(), after: after(), append: append(), before: before(), children: children(), contains: contains(), empty: empty(), find: find()
, … }
ovenplayer.js:2:161609
MESSAGE ::::: offer ovenplayer.provider.WebRTCProvider-0.9.732.js:2:12897
[Message candidates] 
Array(6) [ {…}, {…}, {…}, {…}, {…}, {…} ]
ovenplayer.provider.WebRTCProvider-0.9.732.js:2:9921
cloneCandidate addIceCandidate : success 6 ovenplayer.provider.WebRTCProvider-0.9.732.js:2:12504
[onicecandidate] 
RTCIceCandidate { foundation: "0", component: 1, protocol: "udp", priority: 2122252543, ip: "192.168.1.79", port: 54633, type: "host", toJSON: toJSON()
, candidate: "candidate:0 1 UDP 2122252543 192.168.1.79 54633 typ host", sdpMid: "xsy8ln" }
ovenplayer.provider.WebRTCProvider-0.9.732.js:2:10010
[onicecandidate] 
RTCIceCandidate { foundation: "2", component: 1, protocol: "tcp", priority: 2105524479, ip: "192.168.1.79", port: 9, type: "host", tcpType: "active", toJSON: toJSON()
, candidate: "candidate:2 1 TCP 2105524479 192.168.1.79 9 typ host tcptype active" }
ovenplayer.provider.WebRTCProvider-0.9.732.js:2:10010
[onicecandidate] 
RTCIceCandidate { foundation: "1", component: 1, protocol: "udp", priority: 1686052863, ip: "46.96.4.197", port: 64871, type: "srflx", relatedAddress: "192.168.1.79", relatedPort: 54633, toJSON: toJSON()
 }
ovenplayer.provider.WebRTCProvider-0.9.732.js:2:10010
[onicecandidate] 
RTCIceCandidate { candidate: "", sdpMid: "xsy8ln", sdpMLineIndex: 0, usernameFragment: "8873d531" }
ovenplayer.provider.WebRTCProvider-0.9.732.js:2:10010
Object { code: 501, message: "Connection with low-latency(OME) server failed.", reason: "WebSocket connection failed.", error: "Invalid candidate: " }
ix.html:23:21
`
the same page works fine in chrome and safari

**Comment by dimiden** [comment]
@cheluskin Thank you for your reporting!

This issue is caused by the sending of an empty string of candidate from FireFox, which the server determines to be invalid candidate and denies access.

In the next version, invalid candidate will be ignored and patched to use only the other candidates.

**Comment by Leeaandrob** [comment]
@dimiden do you have this on your to do list to the next release? I would love help this project. How can i begin?

**Comment by dimiden** [comment]
@Leeaandrob We have corrected this issue, including and is testing to push the git. So I'd appreciate it if you could wait a little longer.

If you want to try it now, change the code from the 708 line of the src/projects/rtc_signalling/rtc_signalling_server.cpp file as follows:

Before:
```
...
			ov::String candidate = ov::Converter::ToString(candidate_iterator["candidate"]);
			uint32_t sdp_m_line_index = ov::Converter::ToUInt32(candidate_iterator["sdpMLineIndex"]);
...
```

After
```
...
			ov::String candidate = ov::Converter::ToString(candidate_iterator["candidate"]);

			if (candidate.IsEmpty())
			{
				logtw("[Host -> OME] The host peer sent an empty candidate");
				continue;
			}

			uint32_t sdp_m_line_index = ov::Converter::ToUInt32(candidate_iterator["sdpMLineIndex"]);
...
```

**Comment by Leeaandrob** [comment]
Thanks so much.

I will change this lines and build.

Best regards

**Comment by json-m** [comment]
still experiencing this with the above changes, unable to start playback..

```
[2019-10-15 05:56:07.127] I 27 HttpServer | http_server.cpp:106  | Client([v4] 172.16.69.30:53216) is connected on [v4] 0.0.0.0:3333
[2019-10-15 05:56:07.128] I 27 Signalling | rtc_signalling_server.cpp:94   | New client is connected: <ClientSocket: 0x5655580bda90, #26, state: 4, TCP, [v4] 172.16.69.30:53216>
[2019-10-15 05:56:07.183] W 27 SDP | session_description.cpp:252  | Unknown Attributes : a=sendrecv
[2019-10-15 05:56:07.231] W 27 Signalling | rtc_signalling_server.cpp:712  | [Host -> OME] The host peer sent an empty candidate
```

my src/projects/rtc_signalling/rtc_signalling_server.cpp, L708-716:
```
708                         ov::String candidate = ov::Converter::ToString(candidate_iterator["candidate"]);
709
710                         if (candidate.IsEmpty())
711                         {
712                                 logtw("[Host -> OME] The host peer sent an empty candidate");
713                                 continue;
714                         }
715
716                         uint32_t sdp_m_line_index = ov::Converter::ToUInt32(candidate_iterator["sdpMLineIndex"]);
```

i already had this code, as i am using the `temp/cmaf` branch

Firefox 69.0.3 (64-bit)

**Comment by dimiden** [comment]
@json-m 
This is a known issue, which is caused by P2P-related code execution, even though P2P has been disabled.

It's been modified in the code I'm working on, so it'll be resolved in the next release.

**Comment by Leeaandrob** [comment]
Is it possible use the hls to delivery between 1/3seconds?

Using cmaf Chunked?

Best regards

**Comment by dimiden** [comment]
@Leeaandrob 
OME does not support CMAF chunked transfer based on HLS.

We are currently planning to support Apple's LHLS, and are considering supporting the low-latency HLS proposed by the hls.js.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
