### ISSUE TITLE
RTSP Pull not supporting Basic Auth?

### ISSUE THREAD

**Issue by fcqpl** [AirenSoft/OvenMediaEngine#443]
Hello,
Is RTSP Pull not supporting Basic Auth?
I added url with login and password and looks like OME stripped it.

Is there any other parameters for `<Urls>` or `<Pass>`?

From log:
```
[07-18 03:05:35.697] E [SPRtcSignalling:19] RtspcStream | rtspc_stream.cpp:264  | Rtsp server(rtsp://domain.pl:554/Streaming/Channels/101?transport=tcp) rejected the describe request : 401(Unauthorized)
```

```
<VirtualHost>
	<Origins>
		<Origin>
			<Location>/app/rtsp_pull</Location>
			<Pass>
				<Scheme>rtsp</Scheme>
				<Urls><Url>login:password@domain.pl:554/Streaming/Channels/101</Url></Urls>
			</Pass>
		</Origin>
	</Origins>
	[...]
</VirtualHost>
```

Pls also check logfile - there is something like "Assertion failed" and OME crashed after trying play stream.
[ome-log-crash-rtsp.md](https://github.com/AirenSoft/OvenMediaEngine/files/6835510/ome-log-crash-rtsp.md)

**Comment by getroot** [comment]
@fcqpl 
Unfortunately OME currently does not support rtsp basic auth. I plan to develop this again once the urgent project I'm working on is complete.

I will fix the "assertion failed" issue quickly. Thank you.

**Comment by getroot** [comment]
@fcqpl The assertion failed seems to have resolved the issue. Could you please check if your problem is also solved?

(Assertion failed only occurs when running in debug mode. Do you test OME in debug mode?)

**Comment by SparLaimor** [comment]
We also have a RTSP with authorization. If the issue is resolved, it would be great

**Comment by getroot** [comment]
I will develop the RTSP Basic Auth function not too late.

**Comment by deepsurvey** [comment]
Hello,
Can you confirm that Basic Auth was supported in the past( roughly 1 year ago) and is not yet for the moment?

**Comment by getroot** [comment]
@deepsurvey 

No this was an issue about 6 months ago.  Haha I'm joking, actually, I haven't been able to do it yet because I'm busy with survival.  I'll try, there are so many issues that this might get pushed back again.

**Comment by deepsurvey** [comment]
Thanks for the swift response. I hope survival mode is a positive thing.... although mostly it implies something different. I sure do hope you guys will be able to continue this marvelously great platform. 

I will try to switch off user name and password protection on the camera's and work around the problem. I am lucky that the feeds are only available on a closed LAN and a OME edge brokers the feeds further.

Thank again for the swift response

**Comment by getroot** [comment]
@deepsurvey 
Oh, I didn't mean to be negative. We do commercial projects about half a year and invest half a year in OvenMediaEngine.

**Comment by getroot** [comment]
Thank you for waiting!

I have implemented the RTSP Auth (Basic, Digest) function.
https://github.com/AirenSoft/OvenMediaEngine/commit/ea0f64df618c0955550301e1d862e270066db71f

This function can be used as below.

```
<Origins>
	<Properties>
		<NoInputFailoverTimeout>3000</NoInputFailoverTimeout>
		<UnusedStreamDeletionTimeout>3000</UnusedStreamDeletionTimeout>
	</Properties>
	<Origin>
		<Location>/app/stream</Location>
		<Pass>
			<Scheme>rtsp</Scheme>
			<Urls>
				<Url>airen:airen@192.168.0.160:8554/app/stream</Url>
			</Urls>
		</Pass>
	</Origin>
</Origins>
```

Please check if it works well, and let me know if there are any problems!

**Comment by fcqpl** [comment]
Thanks @getroot!
It's still not working with Hikvision and Dahua camera.
I can expose 554 port for tests.
Camera has enabled digest/basic auth.

```
ovenmediaengine_1  | [2022-01-27 21:46:54.971] E [SPRtcSig-T3334:14] RtspcStream | rtspc_stream.cpp:261  | Rtsp server(rtsp://x.y.z.70:554/Streaming/Channels/101/2) rejected the describe request : 401(Unauthorized)
ovenmediaengine_1  | [2022-01-27 21:46:55.076] E [SPRtcSig-T3334:14] RtspcStream | rtspc_stream.cpp:261  | Rtsp server(rtsp://x.y.z.71:554/cam/realmonitor?channel=1&subtype=1) rejected the describe request : 401(Unauthorized)
```

**Comment by getroot** [comment]
@fcqpl Could you give me access to your rtsp server for debugging?  If possible, please send it to support@airensoft.com

**Comment by getroot** [comment]
@fcqpl 
I looked again at the log you posted and found that you are still using the old version. (The latest **dev** version has changed log messages.)

Please compile and use the master branch or test it using airensoft/ovenmediaengine:dev.

If that doesn't work, I'd appreciate it if you could give me access to your rtsp server for debugging.

**Comment by fcqpl** [comment]
@getroot 
Oops, sorry, my fault :)
I used latest tag instead dev.

But after upgrade it's still not working with Hikvision Camera:
ovenmediaengine_1  | [2022-01-28 22:49:43.027] E [StreamCollector:21] RtspcStream | rtspc_stream.cpp:667  | No response(CSeq : 3) was received from the rtsp server(rtsp://x.y.z.70:554/Streaming/Channels/101/)

I will send you access to rtsp.

**Comment by getroot** [comment]
This is probably because authentication succeeded, but another error occurred.  I look forward to your mail.  Thank you!

**Comment by getroot** [comment]
@fcqpl 
I haven't received the email yet. Did you send me an e-mail? If you sent an e-mail, could you check if it was sent to support@airensoft.com?

**Comment by fcqpl** [comment]
@getroot Sorry, I haven't had any free time yet. I will try to send it as soon as possible.

**Comment by getroot** [comment]
@fcqpl No problem! Thank you!

**Comment by deepsurvey** [comment]
Hello,
Sorry for the delay, due to a project I had to go with the unprotected feeds. So I have updated OME to the lastest MASTER build and can play protected feeds. Authentication works. 

Starting ovenmediaengine_origin_1 ... done
Attaching to ovenmediaengine_origin_1
origin_1  | [2022-04-01 08:29:25.230] W [OvenMediaEngine:1] Config | config_manager.cpp:158  | There is no configuration file for logs : origin_conf/Logger.xml. OME will run with the default settings.
origin_1  | [2022-04-01 08:29:25.230] I [OvenMediaEngine:1] Config | config_manager.cpp:227  | Trying to load configurations... (origin_conf/Server.xml)
origin_1  | [2022-04-01 08:29:25.263] I [OvenMediaEngine:1] OvenMediaEngine | banner.cpp:23   | OvenMediaEngine v0.13.2 () is started on [91bd258a68be] (Linux x86_64 - 5.13.0-39-generic, #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022)



origin_1  | [2022-04-01 08:29:25.681] I [SPRtcSig-T3333:8] HttpServer | http_server.cpp:146  | Client(<ClientSocket: 0x7f2c240012d0, #38, Connected, TCP, Nonblocking, 172.26.248.17:38302>) is connected on *:3333
origin_1  | [2022-04-01 08:29:25.682] I [SPRtcSig-T3333:8] HttpServer | http_transaction.cpp:112  | Client(<ClientSocket: 0x7f2c240012d0, #38, Connected, TCP, Nonblocking, 172.26.248.17:38302>) is requested uri: [http://172.26.0.235:3333/volans/fwd]
origin_1  | [2022-04-01 08:29:25.682] I [SPRtcSig-T3333:8] Signalling | rtc_signalling_server.cpp:231  | New client is connected: <ClientSocket: 0x7f2c240012d0, #38, Connected, TCP, Nonblocking, 172.26.248.17:38302>
origin_1  | [2022-04-01 08:29:25.746] I [SPRtcSig-T3333:8] Orchestrator | orchestrator.cpp:682  | Trying to pull stream [#default#volans/fwd] from provider using origin map: PullProvider
origin_1  | [2022-04-01 08:29:25.908] I [SPRtcSig-T3333:8] RtspcStream | rtspc_stream.cpp:355  | SDP : v=0
origin_1  | o=- 6401418138330697512 1 IN IP4 192.168.10.200
origin_1  | s=Session streamed with GStreamer
origin_1  | i=rtsp-server
origin_1  | t=0 0
origin_1  | a=tool:GStreamer
origin_1  | a=type:broadcast
origin_1  | a=range:npt=now-
origin_1  | a=control:rtsp://192.168.10.200:554/axis-media/media.amp
origin_1  | m=video 0 RTP/AVP 96
origin_1  | c=IN IP4 0.0.0.0
origin_1  | b=AS:50000
origin_1  | a=rtpmap:96 H264/90000
origin_1  | a=fmtp:96 packetization-mode=1;profile-level-id=640029;sprop-parameter-sets=Z2QAKa0AxSAyBN+XAW4CAgNKACky4AM3+YAeJEVA,aO48sA==
origin_1  | a=ts-refclk:local
origin_1  | a=mediaclk:sender
origin_1  | a=recvonly
origin_1  | a=control:rtsp://192.168.10.200:554/axis-media/media.amp/stream=0
origin_1  | a=framerate:10.000000
origin_1  | a=transform:0.750000,0.000000,0.000000;0.000000,1.000000,0.000000;0.000000,0.000000,1.000000
origin_1  | 
origin_1  | 
origin_1  | [2022-04-01 08:29:26.018] I [SPRtcSig-T3333:8] Provider | stream.cpp:53   | RTSPCProvider Application has started to play [fwd(100)] stream : rtsp://192.168.10.200:554/axis-media/media.amp
origin_1  | [2022-04-01 08:29:26.018] I [SPRtcSig-T3333:8] Provider | stream.cpp:49   | #default#volans/fwd(100) has been started stream
origin_1  | [2022-04-01 08:29:26.018] I [SPRtcSig-T3333:8] Provider | application.cpp:129  | #default#volans application has created 0 stream motor
origin_1  | [2022-04-01 08:29:26.018] I [SPRtcSig-T3333:8] MediaRouter | mediarouter_application.cpp:244  | Trying to create a stream: [#default#volans/fwd(100)]
origin_1  | [2022-04-01 08:29:26.018] I [SPRtcSig-T3333:8] MediaRouter | mediarouter_application.cpp:245  | 
origin_1  | [Stream Info]
origin_1  | id(100), msid(0), output(fwd), SourceType(RtspPull), Created Time (Fri Apr  1 08:29:25 2022) UUID(40cacafd-b217-4247-a032-be7bef88ff57/default/#default#volans/fwd/i)
origin_1  | 
origin_1  | 	Video Track #0: Bypass(false) Bitrate(0b) codec(1, H264) resolution(0x0) framerate(0.00fps) timebase(1/90000)
origin_1  | [2022-04-01 08:29:26.018] I [SPRtcSig-T3333:8] MediaRouter | mediarouter_stream.cpp:54   | Trying to create media route stream: name(fwd) id(100)
origin_1  | [2022-04-01 08:29:26.018] I [SPRtcSig-T3333:8] Monitor | application_metrics.cpp:57   | Create StreamMetrics(fwd/40cacafd-b217-4247-a032-be7bef88ff57/default/#default#volans/fwd/i) for monitoring

**Comment by fcqpl** [comment]
@getroot
https://github.com/AirenSoft/OvenMediaEngine/issues/443#issuecomment-1024725779

After 3 months i got some time for tests ;)
Strange, but it's working now correctly with Hikvision camera.
We can close this issue, everything is ok.
