### ISSUE TITLE
TLS Issue on latest commits

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#518]
Hi guys, from the commits in the last 24 hours there seems to be a problem with OpenSSL?

Going back to 0.12.5 the same certificate works just fine, but in the current master I am getting a generic websocket error client-side and this error server side:

```
[2021-09-23 11:06:49.219] E [SPthumb_https-T:48] OpenSSL | tls.cpp:132  | Invalid TLS certificate
[2021-09-23 11:06:49.219] E [SPthumb_https-T:48] TLS | tls_server_data.cpp:58   | Could not initialize TLS: [OpenSSL] error:00000000:lib(0)::reason(0) (0)
```

Normally if there is an issue with the certificate, OME has a problem right at the start, but it seemed to pass fine and the API server is working:

```
[2021-09-23 11:02:34.327] I [OvenMediaEngine:1085] OvenMediaEngine | main.cpp:69   | Server ID : 24d5845c-df91-4412-8034-a874bb46b30a
[2021-09-23 11:02:34.327] I [OvenMediaEngine:1085] Certificate | certificate.cpp:70   | Trying to create a certificate using
	Cert file path: /etc/letsencrypt/live/myomeinstance.com/cert.pem
	Chain cert file path: /etc/letsencrypt/live/myomeinstance.com/chain.pem
	Private key file path: /etc/letsencrypt/live/myomeinstance.com/privkey.pem
[2021-09-23 11:02:34.334] I [OvenMediaEngine:1085] Certificate | certificate.cpp:70   | Trying to create a certificate using
	Cert file path: /etc/letsencrypt/live/myomeinstance.com/cert.pem
	Chain cert file path: /etc/letsencrypt/live/myomeinstance.com/chain.pem
	Private key file path: /etc/letsencrypt/live/myomeinstance.com/privkey.pem
[2021-09-23 11:02:34.337] I [OvenMediaEngine:1085] APIServer | api_server.cpp:123  | API Server is listening on TLS: *:8082/TCP...

```

Full log file:  [engine-6.log](https://github.com/AirenSoft/OvenMediaEngine/files/7217238/engine-6.log)

Finally, I went back to some recent builds of 0.12.5 in the same environment, and confirmed the certificate works in older builds.

Please let me know if I can provide any further info, thanks!

**Comment by dimiden** [comment]
@bchah 
Could you check out the commit version that works normally?
It would be very helpful if you could attach a line that displays version information when executing OME.
```
[09-23 13:50:13.159] I [OvenMediaEngine:2001649] OvenMediaEngine | banner.cpp:28   | OvenMediaEngine v0.12.5 (v0.12.5-20-gf5fb60be) [debug] is started on [OME-Dev] (Linux x86_64 - 5.11.0-27-generic, #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021)
```

In addition, I recently changed the auto-generated config from ```LastConfig.json``` to ```LastConfig.xml``` when calling some API. Please also attach ```LastConfig.json``` and ```LastConfig.xml``` to check if this is a related problem.

**Comment by bchah** [comment]
Hi @dimiden thank you for the response.

Here is the line you are looking for:

`[2021-09-23 10:57:04.615] I [OvenMediaEngine:512] OvenMediaEngine | banner.cpp:28   | OvenMediaEngine v0.12.5 (v0.12.5-25-g1e5ba8b4) is started on [myomeinstance.com] (Linux x86_64 - 5.4.0-81-generic, #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021)`

Where would I find the LastConfig.json / xml files please? I only have the Server.xml and Server.id :(

**Comment by dimiden** [comment]
@bchah 
Thank you for the information. I found that there are some problems on commit 091b0bb5c080b44a7702a18e405a4e43a581efbe and 62e52ea4175e451b89ea24d3afd58bfc4d0884fa.

This is a problem that occurred from the ```<VirtualHost include="VHost*.xml" />```setting, which was ignored in the old version, but the newly changed version confirmed that empty ```<VirtualHost>``` was created by parsing this item incorrectly.
Currently, OME does not implemented TLS SNI specification, so only the TLS certificate of the first ```<VirtualHost>``` is used, but there is a problem that initialization of the TLS certificate fails as the empty ```<VirtualHost>``` item is referenced.

I'm going to fix this problem quickly!

**Comment by bchah** [comment]
Thank you very much @dimiden !! I hope it is not too much work, thank you as always for your development effort 💯

**Comment by dimiden** [comment]
I fixed this problem and confirmed that it works well. :) If it doesn't work properly, please reopen this issue!

**Comment by bchah** [comment]
Sorry @dimiden but I am still getting the same errors:

`[2021-09-23 14:47:43.208] I [OvenMediaEngine:512] OvenMediaEngine | banner.cpp:28   | OvenMediaEngine v0.12.5 (v0.12.5-25-g1e5ba8b4) is started on [myomeinstance.com] (Linux x86_64 - 5.4.0-81-generic, #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021)`

Full log:
[engine-8.log](https://github.com/AirenSoft/OvenMediaEngine/files/7218674/engine-8.log)

![Screen Shot 2021-09-23 at 10 56 29 AM](https://user-images.githubusercontent.com/33604674/134531393-c6fced40-18d6-486e-b97a-209cabd62294.jpg)

**Comment by getroot** [comment]
@bchah The problem no longer reproduces in my environment. Try clearing the docker image and using airensoft/ovenmediaengine:dev?

**Comment by bchah** [comment]
Hmm, I do not use the public docker images - I use the master build script in a fresh container every time. I will keep trying on different systems from my usual build system.

**Comment by dimiden** [comment]
@bchah
I noticed your OME version is v0.12.5-25-g1e5ba8b4. Since it has the problem, please check your docker image.

**Comment by bchah** [comment]
Thank you @dimiden - you're right, it definitely helped when I used the new build instead of the old one 🤣. My mistake.

This issue is done! 🥇
